dist: trusty
sudo: false
language: node_js
node_js:
  - "7"

addons:
  firefox: latest

env:
  - NIGHTWATCH_ENV=
  - NIGHTWATCH_ENV=chrome

matrix:
  allow_failures:
    - env: "NIGHTWATCH_ENV=chrome"

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - jdk_switcher use oraclejdk8
